# Generated by Django 5.0.1 on 2024-10-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measurement_unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('dona', 'Dona'), ('l', 'Litr'), ('m', 'Metr')], default='kg', max_length=50, verbose_name='Birlik'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx: $'),
        ),
    ]
