# Generated by Django 5.0.1 on 2024-10-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_is_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='information',
            field=models.TextField(blank=True, default="Ma'lumot yo'q", null=True),
        ),
    ]
